export const CACHE_NAMESPACES = {
  TAGS: "tags",
  EVENTS: "events",
  USERS: "users",
  THREADS: "threads",
  MESSAGES: "messages",
  SESSIONS: "sessions",
  MEDIA: "media",
};

export const DEFAULT_NAMESPACE_CACHE_TTL = {
  [CACHE_NAMESPACES.TAGS]: 3600 * 24,
  [CACHE_NAMESPACES.EVENTS]: 3600 * 24,
  [CACHE_NAMESPACES.USERS]: 3600,
  [CACHE_NAMESPACES.THREADS]: 3600 * 24,
  [CACHE_NAMESPACES.MESSAGES]: 3600 * 24 * 2,
  [CACHE_NAMESPACES.SESSIONS]: 3600 * 24 * 30,
  [CACHE_NAMESPACES.MEDIA]: 3600 * 24,
};
